spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9701/eureka/
server:
  port: 9702
